version: '4'  # バージョンを適切なバージョンに設定

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - .:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8001:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app

  db:
    platform: linux/x86_64
    image: mysql:8.0.19
    container_name: to_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/to_db/data:/var/lib/mysql
      - ./docker/to_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/to_db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
      